version: '3.8'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB= 
      - POSTGRES_USER= 
      - POSTGRES_PASSWORD= 

  spring-app:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: backend-portfolio:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: 
      aws_key: 
      aws_secret: 
      aws_region: 
      aws_bucket: 
    depends_on:
      - postgres-db

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # image: frontend-portfolio:latest
    ports:
      - "9090:9090"
    depends_on:
      - spring-app
